# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.srcs/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0.xci
# IP: The module: 'mb_unit_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.gen/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_unit_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.gen/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_unit_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.gen/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_unit_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.srcs/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0.xci
# IP: The module: 'mb_unit_axi_uartlite_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.gen/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_unit_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.gen/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_unit_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/carri/ECE_385/NES_Emulator/NES_Emulator.gen/sources_1/bd/mb_unit/ip/mb_unit_axi_uartlite_0_0/mb_unit_axi_uartlite_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_unit_axi_uartlite_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
